### ISSUE TITLE
Redesign in tandem with OpenReferral.org and CfA's OR page

### ISSUE THREAD

**Issue by greggish** [codeforamerica/ohanapi.org#2]
Among other edits, we want to explain (with both text and visual) the relationship between Ohana and Open Referral. 

For example, we discussed a banner that says: 
Are you a software developer? --> Build the Platform (Github)
Are you a community leader? --> Shape the Standard (OpenReferral.org)

We also want a segment of the vertical scroll that explains the relationship between Ohana and Open Referral (and links either to CfA's page or the OpenReferral.org or both). I can get text for that when you're ready.

Finally, we have new apps using Ohana. Able to give you logos when ready.

**Comment by anselmbradford** [comment]
(A) Text has been added to ohanapi.org. I'd suggest we consider closing this repo down to reduce the number of sites with ohana/open referral information. See https://github.com/codeforamerica/ohanapi.org/issues/7
