### ISSUE TITLE
Update README instructions

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/ohanapi.org#4]
I had trouble running `grunt watch` on my machine. I had to install the CLI tool to get it to work, per the [Grunt Getting Started guide](http://gruntjs.com/getting-started):
```
npm install -g grunt-cli
```
Also, the README should point out that Node.js is a prerequisite.

**Comment by anselmbradford** [comment]
For reference, I opened an issue to create a how-to for this at https://github.com/codeforamerica/howto/issues/14, but perhaps it's too simple to have its own.
